### ISSUE TITLE
Cannot run production mode with webhooks

### ISSUE THREAD

**Issue by waclock** [telegram-bot-rb/telegram_bot_app#10]
Hello, I can't seem to setup the rake tasks to work, I've changed my production.rb file, but can't get it to work. Here's the trace

```
/Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/cache/file_store.rb:22:in `initialize': wrong number of arguments (given 0, expected 1..2) (ArgumentError)
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/cache.rb:60:in `new'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/cache.rb:60:in `lookup_store'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/bundler/gems/telegram-bot-17260cb5a9e1/lib/telegram/bot/updates_controller/session.rb:82:in `session_store='
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/bundler/gems/telegram-bot-17260cb5a9e1/lib/telegram/bot/railtie.rb:21:in `block (2 levels) in <class:Railtie>'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:69:in `instance_eval'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:49:in `each'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/bundler/gems/telegram-bot-17260cb5a9e1/lib/telegram/bot/updates_controller.rb:211:in `<class:UpdatesController>'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/bundler/gems/telegram-bot-17260cb5a9e1/lib/telegram/bot/updates_controller.rb:53:in `<module:Bot>'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/bundler/gems/telegram-bot-17260cb5a9e1/lib/telegram/bot/updates_controller.rb:6:in `<module:Telegram>'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/bundler/gems/telegram-bot-17260cb5a9e1/lib/telegram/bot/updates_controller.rb:5:in `<top (required)>'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:257:in `block in load_dependency'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:662:in `new_constants_in'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
	from /Users/johnpeebles/quantic/telegram_bot_app/app/controllers/telegram_webhooks_controller.rb:1:in `<top (required)>'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:477:in `load'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:477:in `block in load_file'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:662:in `new_constants_in'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:476:in `load_file'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:375:in `block in require_or_load'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies/interlock.rb:11:in `loading'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:37:in `load_interlock'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:358:in `require_or_load'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:336:in `depend_on'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:252:in `require_dependency'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/engine.rb:475:in `each'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/engine.rb:475:in `block in eager_load!'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/engine.rb:473:in `each'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/engine.rb:473:in `eager_load!'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/engine.rb:354:in `eager_load!'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/application/finisher.rb:59:in `each'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/application/finisher.rb:59:in `block in <module:Finisher>'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/initializable.rb:30:in `run'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/johnpeebles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/johnpeebles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/johnpeebles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/johnpeebles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/johnpeebles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/johnpeebles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/johnpeebles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/johnpeebles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/johnpeebles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/application.rb:352:in `initialize!'
	from /Users/johnpeebles/quantic/telegram_bot_app/config/environment.rb:5:in `<top (required)>'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/spring-2.0.2/lib/spring/application.rb:102:in `require'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/spring-2.0.2/lib/spring/application.rb:102:in `preload'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/johnpeebles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/johnpeebles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
➜  telegram_bot_app git:(master)
```
  
My secrets.yml is updated, and the bot does run without problems in development mode, however my main goal is to integrate this bot into an existing rails app, and I was hoping webhooks was the answer to that. If it isn't a heads up would be greatly appreciated

**Comment by printercu** [comment]
Hi! The problem seems to be in session store configuration. Please update to the latest release of telegram-bot, there was some commits related to providing more relevant errors in such cases.

**Comment by waclock** [comment]
Thanks for your response, I updated to the last version of telegram-bot, I still face the same issue.

```
/Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/cache/file_store.rb:22:in `initialize': wrong number of arguments (given 0, expected 1..2) (ArgumentError)
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/cache.rb:60:in `new'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/cache.rb:60:in `lookup_store'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/bundler/gems/telegram-bot-384d203b5934/lib/telegram/bot/updates_controller/session.rb:89:in `session_store='
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/bundler/gems/telegram-bot-384d203b5934/lib/telegram/bot/railtie.rb:21:in `block (2 levels) in <class:Railtie>'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:69:in `instance_eval'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:49:in `each'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/bundler/gems/telegram-bot-384d203b5934/lib/telegram/bot/updates_controller.rb:218:in `<class:UpdatesController>'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/bundler/gems/telegram-bot-384d203b5934/lib/telegram/bot/updates_controller.rb:53:in `<module:Bot>'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/bundler/gems/telegram-bot-384d203b5934/lib/telegram/bot/updates_controller.rb:6:in `<module:Telegram>'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/bundler/gems/telegram-bot-384d203b5934/lib/telegram/bot/updates_controller.rb:5:in `<top (required)>'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:257:in `block in load_dependency'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:662:in `new_constants_in'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
	from /Users/johnpeebles/quantic/telegram_bot_app/app/controllers/telegram_webhooks_controller.rb:1:in `<top (required)>'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:477:in `load'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:477:in `block in load_file'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:662:in `new_constants_in'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:476:in `load_file'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:375:in `block in require_or_load'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies/interlock.rb:11:in `loading'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:37:in `load_interlock'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:358:in `require_or_load'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:336:in `depend_on'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:252:in `require_dependency'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/engine.rb:475:in `each'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/engine.rb:475:in `block in eager_load!'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/engine.rb:473:in `each'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/engine.rb:473:in `eager_load!'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/engine.rb:354:in `eager_load!'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/application/finisher.rb:59:in `each'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/application/finisher.rb:59:in `block in <module:Finisher>'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/initializable.rb:30:in `run'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/johnpeebles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/johnpeebles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/johnpeebles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/johnpeebles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/johnpeebles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/johnpeebles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/johnpeebles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/johnpeebles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/johnpeebles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/railties-5.0.6/lib/rails/application.rb:352:in `initialize!'
	from /Users/johnpeebles/quantic/telegram_bot_app/config/environment.rb:5:in `<top (required)>'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/spring-2.0.2/lib/spring/application.rb:102:in `require'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/spring-2.0.2/lib/spring/application.rb:102:in `preload'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /Users/johnpeebles/.rvm/gems/ruby-2.3.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/johnpeebles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/johnpeebles/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

The line that's failing is this one:

```
          def session_store=(store)
            config.session_store = ActiveSupport::Cache.lookup_store(store)
          end
```
however I'm not sure how to fix it. My session store looks like this
`Rails.application.config.session_store :cookie_store, key: '_telegram_bot_app_session'
`

**Comment by waclock** [comment]
I've pushed my project to https://github.com/waclock/telegram_bot_app in case you want to take a look.

**Comment by printercu** [comment]
Thank you for sharing sample app! I've found that I had configured FileStore incorrectly. It requires path to store directory, I've added note about deployment and fix in https://github.com/telegram-bot-rb/telegram_bot_app/commit/1dc7b656bb730cf4a01e36eee06057070741ff3e

Please give it a try.

**Comment by printercu** [comment]
Can this issue be closed?

**Comment by waclock** [comment]
Yes, sorry for not closing it before.
