### ISSUE TITLE
demo app not allowing console to start

### ISSUE THREAD

**Issue by dvodvo** [telegram-bot-rb/telegram_bot_app#24]
Upon `bundle exec rails c`  
```
Loading development environment (Rails 5.0.6)
warning: setting prompt with help of `Pry.config.prompt = [proc {}, proc {}]` is deprecated. Use Pry::Prompt API instead
[...]
2: from [...].rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/pry-0.13.1/lib/pry/pry_instance.rb:692:in `generate_prompt'
1: from [...].rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/debbie-2.0.0/lib/debbie/railtie.rb:53:in `block (3 levels) in <class:Railtie>'
```
with error: `undefined method `input_array' for #<Pry:0x00007fafec35a7c0> (NoMethodError)` 
The file's lines 51 to 62 are:
```
Pry.config.prompt = [
  ->(object, level, pry) do      # Main prompt
  "#{line.(pry)}#{colored_name.()}#{target_string.(object, level)} #{separator.()}  "
end,
 ->(object, level, pry) do      # Wait prompt in multiline input
   spaces = ' ' * (
      "[#{pry.input_array.size}] ".size +  # Uncolored `line.(pry)`
      name.size +
      target_string.(object, level).size
    )
    "#{spaces} #{separator.()}  "
end

```
I haven't been using Pry, so I am not certain how to approach/overcome this.

**Comment by printercu** [comment]
Hi! I've updated master branch to rails 5.2, this change also contains fix for the issue. Old code is in the `rails50` branch, I've pushed fix there as well. Or you can just remove `debbie` gem from the local gemfile and run `bundle install` to get rid of pry.
