### ISSUE TITLE
Communication issue while running in development mode

### ISSUE THREAD

**Issue by kirantpatil** [telegram-bot-rb/telegram_bot_app#6]
Hi,

I am getting message on console when running in development mode as below. I am not getting any message in my bot when I use /start.

Also running rails s command as below.

### $ rails s
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
=> Booting Puma
=> Rails 5.0.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/arguments.rb:38: warning: constant ::Fixnum is deprecated
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/arguments.rb:38: warning: constant ::Bignum is deprecated
Puma starting in single mode...
* Version 3.6.2 (ruby 2.4.1-p111), codename: Sleepy Sunday Serenity
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop

### $ bundle exec rake telegram:bot:poller
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/arguments.rb:38: warning: constant ::Fixnum is deprecated
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/arguments.rb:38: warning: constant ::Bignum is deprecated
Started bot poller.

execution expired
/home/fueb/.rvm/gems/ruby-2.4.1/gems/httpclient-2.8.3/lib/httpclient/session.rb:611:in `initialize'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/httpclient-2.8.3/lib/httpclient/session.rb:611:in `new'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/httpclient-2.8.3/lib/httpclient/session.rb:611:in `create_socket'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:21:in `create_socket'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/httpclient-2.8.3/lib/httpclient/session.rb:752:in `block in connect'
/home/fueb/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/httpclient-2.8.3/lib/httpclient/session.rb:748:in `connect'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/httpclient-2.8.3/lib/httpclient/session.rb:511:in `query'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/httpclient-2.8.3/lib/httpclient.rb:765:in `post'
/home/fueb/.rvm/gems/ruby-2.4.1/bundler/gems/telegram-bot-109811882665/lib/telegram/bot/client.rb:105:in `http_request'
/home/fueb/.rvm/gems/ruby-2.4.1/bundler/gems/telegram-bot-109811882665/lib/telegram/bot/client.rb:50:in `request'
/home/fueb/.rvm/gems/ruby-2.4.1/bundler/gems/telegram-bot-109811882665/lib/telegram/bot/async.rb:156:in `request'
/home/fueb/.rvm/gems/ruby-2.4.1/bundler/gems/telegram-bot-109811882665/lib/telegram/bot/client.rb:98:in `block (2 levels) in <class:Client>'
/home/fueb/.rvm/gems/ruby-2.4.1/bundler/gems/telegram-bot-109811882665/lib/telegram/bot/updates_poller.rb:67:in `block in fetch_updates'
/home/fueb/.rvm/gems/ruby-2.4.1/bundler/gems/telegram-bot-109811882665/lib/telegram/bot/async.rb:143:in `async'
/home/fueb/.rvm/gems/ruby-2.4.1/bundler/gems/telegram-bot-109811882665/lib/telegram/bot/updates_poller.rb:67:in `fetch_updates'
/home/fueb/.rvm/gems/ruby-2.4.1/bundler/gems/telegram-bot-109811882665/lib/telegram/bot/updates_poller.rb:48:in `start'
/home/fueb/.rvm/gems/ruby-2.4.1/bundler/gems/telegram-bot-109811882665/lib/telegram/bot/updates_poller.rb:21:in `start'
/home/fueb/.rvm/gems/ruby-2.4.1/bundler/gems/telegram-bot-109811882665/lib/tasks/telegram-bot.rake:12:in `block (3 levels) in <top (required)>'
/home/fueb/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/fueb/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/fueb/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/fueb/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/fueb/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/fueb/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/fueb/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/fueb/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/fueb/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/fueb/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/fueb/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/fueb/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/fueb/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/fueb/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/home/fueb/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/fueb/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/fueb/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/fueb/.rvm/rubies/ruby-2.4.1/bin/rake:22:in `load'
/home/fueb/.rvm/rubies/ruby-2.4.1/bin/rake:22:in `<top (required)>'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `load'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/lib/bundler/cli/exec.rb:27:in `run'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/lib/bundler/cli.rb:360:in `exec'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/lib/bundler/cli.rb:20:in `dispatch'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/lib/bundler/cli.rb:10:in `start'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/exe/bundle:35:in `block in <top (required)>'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.1/exe/bundle:27:in `<top (required)>'
/home/fueb/.rvm/gems/ruby-2.4.1/bin/bundle:22:in `load'
/home/fueb/.rvm/gems/ruby-2.4.1/bin/bundle:22:in `<main>'
/home/fueb/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/home/fueb/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

### ps -x command output
-------------------
25694 pts/5    Ss     0:00 -bash
25979 pts/4    Sl+    0:02 /home/fueb/.rvm/rubies/ruby-2.4.1/bin/rake telegram:bot:poller
26008 pts/5    Sl+    0:02 puma 3.6.2 (tcp://localhost:3000) [telegram_bot_app]

**Comment by kirantpatil** [comment]
After submitting this issue, it started working. Thanks.
