### ISSUE TITLE
ActiveJob::SerializationError: Unsupported argument type: File

### ISSUE THREAD

**Issue by kirantpatil** [telegram-bot-rb/telegram_bot_app#8]
$ bin/rake telegram:bot:set_webhook RAILS_ENV=production CERT="webhook_cert.pem"

Above command is resulting in below error.
```

$ bin/rake telegram:bot:set_webhook RAILS_ENV=production CERT="webhook_cert.pem"

/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/arguments.rb:38: warning: constant ::Fixnum is deprecated
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/arguments.rb:38: warning: constant ::Bignum is deprecated
Running via Spring preloader in process 6435
Setting webhook for default...
rake aborted!
ActiveJob::SerializationError: Unsupported argument type: File
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/arguments.rb:83:in `serialize_argument'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/arguments.rb:116:in `block in serialize_hash'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/arguments.rb:115:in `each'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/arguments.rb:115:in `each_with_object'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/arguments.rb:115:in `serialize_hash'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/arguments.rb:79:in `serialize_argument'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/arguments.rb:44:in `block in serialize'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/arguments.rb:44:in `map'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/arguments.rb:44:in `serialize'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/core.rb:124:in `serialize_arguments'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/core.rb:81:in `serialize'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/queue_adapters/async_adapter.rb:64:in `initialize'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/queue_adapters/async_adapter.rb:38:in `new'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/queue_adapters/async_adapter.rb:38:in `enqueue'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/enqueuing.rb:76:in `block in enqueue'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:126:in `call'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/logging.rb:15:in `block (3 levels) in <module:Logging>'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/logging.rb:44:in `block in tag_logger'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/tagged_logging.rb:69:in `tagged'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/logging.rb:44:in `tag_logger'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/logging.rb:14:in `block (2 levels) in <module:Logging>'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `instance_exec'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:391:in `block in make_lambda'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:447:in `block in around'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:455:in `call'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:750:in `_run_enqueue_callbacks'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/enqueuing.rb:72:in `enqueue'
/home/fueb/.rvm/gems/ruby-2.4.1/gems/activejob-5.0.1/lib/active_job/enqueuing.rb:18:in `perform_later'
/home/fueb/.rvm/gems/ruby-2.4.1/bundler/gems/telegram-bot-109811882665/lib/telegram/bot/async.rb:158:in `request'
/home/fueb/.rvm/gems/ruby-2.4.1/bundler/gems/telegram-bot-109811882665/lib/telegram/bot/client.rb:98:in `block (2 levels) in <class:Client>'
/home/fueb/.rvm/gems/ruby-2.4.1/bundler/gems/telegram-bot-109811882665/lib/tasks/telegram-bot.rake:24:in `block (4 levels) in <top (required)>'
/home/fueb/.rvm/gems/ruby-2.4.1/bundler/gems/telegram-bot-109811882665/lib/tasks/telegram-bot.rake:20:in `each'
/home/fueb/.rvm/gems/ruby-2.4.1/bundler/gems/telegram-bot-109811882665/lib/tasks/telegram-bot.rake:20:in `block (3 levels) in <top (required)>'
-e:1:in `<main>'
Tasks: TOP => telegram:bot:set_webhook
(See full trace by running task with --trace)

```

**Comment by kirantpatil** [comment]
Here is my cert file.

$ cat webhook_cert.pem 
-----BEGIN CERTIFICATE-----
MIID/zCCAuegAwIBAgIJANR5kY4/AfoNMA0GCSqGSIb3DQEBCwUAMIGVMQswCQYD
VQQGEwJJTjESMBAGA1UECAwJS2FybmF0YWthMRIwEAYDVQQHDAlCZW5nYWx1cnUx
DDAKBgNVBAoMA0dUVDERMA8GA1UECwwIU09GVFdBUkUxFzAVBgNVBAMMDjE3Mi4x
MDQuNDEuMjM2MSQwIgYJKoZIhvcNAQkBFhVraXJhbnRwYXRpbEBnbWFpbC5jb20w
HhcNMTcxMDA1MDkyMjU4WhcNMjcxMDAzMDkyMjU4WjCBlTELMAkGA1UEBhMCSU4x
EjAQBgNVBAgMCUthcm5hdGFrYTESMBAGA1UEBwwJQmVuZ2FsdXJ1MQwwCgYDVQQK
DANHVFQxETAPBgNVBAsMCFNPRlRXQVJFMRcwFQYDVQQDDA4xNzIuMTA0LjQxLjIz
NjEkMCIGCSqGSIb3DQEJARYVa2lyYW50cGF0aWxAZ21haWwuY29tMIIBIjANBgkq
hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoqBwyHoJ/JixcVruPol8ECMxwFNuL18G
u+sZWhAvUuSLzryZ0a/eZp9AuYM9IrxO1zu8G71vNSp9tIxioOm641k6wgQeh6gL
no5o35i4TjmGKyljtJIUFpjzC/upnKjXBMnU3tRgPZf9Ta0RwLwzDKwFXDm3ZkEX
kruIGnnfuNc9t026wbTo/6duN07L/+7dBKWyCDryuZiAQaORQ6AJ77DeA3r1gi36
mL9XWe4u8wNvkJEDGaufCOaOiuaej97OYiXsQt5gQCnATC/3J8MmXvU1tckhlkPG
t+Kia13igMgjeyuYuQm/BCYRMQbUaZuIIQZKJa2py7OdnqnkZgMBjQIDAQABo1Aw
TjAdBgNVHQ4EFgQUGCb7SUnqeIXJOanxRCSK+QuI120wHwYDVR0jBBgwFoAUGCb7
SUnqeIXJOanxRCSK+QuI120wDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
AQEAHCim01EwvgsP7COM1x50n9Ek6zJj2HuGjWR7vYJE0BHEWtoX6GlRj21YMUei
S3llSeDvzGTf6fHS1xON/fyCwoTnB0LgtvhxpH/W+sOSkiZ6Yv4iar7dnuaIZ+5e
p17khX+XNBrcyURCwi5cR3RDzPILq9FLHAElXQJL/1jnholadppi/sfaIjfuUgiZ
Kzkg02JUQqu1sSE8YbiNdi6Cp3VLgaNLq0bpMzZEKRAQsb0dk1MqtQ2TTA9yalKG
mJ7cFGBzHpwCO8wfTl2CppJa452aP05N2GBUo59VXpY5vU+qhEPQzwCNa1oarXYx
QindRg/z1lCA5CHAxSlOCO319g==
-----END CERTIFICATE-----

**Comment by kirantpatil** [comment]
From the below site, it looks like we need to pass the absolute path of the cert.pem file rather file content.

http://snakelab.cc/2016/10/28/telegram_gem_and_self_signed_cert.html

**Comment by printercu** [comment]
Fixed with https://github.com/telegram-bot-rb/telegram-bot/commit/df7039326d3b1711ad858205d27bff38786311fd
